### ISSUE TITLE
Broken link on Readme.md

### ISSUE THREAD

**Issue by pedrohba1** [ora-io/awesome-uniswap-hooks#62]
This link mention does not work

https://uniswaphooks.com/blog/getting-started-with-v4-template

**Comment by AndreiD** [comment]
the repo is dead. I made a new one here _> https://github.com/AndreiD/awsome-uniswap-v4-resources

**Comment by fewwwww** [comment]
The link should be working now (uniswaphooks.com fixed this issue).
